GoogleCloudPlatform/terraform-google-enterprise-application

Makefile
README.md
build/int.cloudbuild.yaml
examples/simple_example/README.md
examples/simple_example/main.tf
examples/simple_example/outputs.tf
examples/simple_example/variables.tf
test/integration/simple_example/simple_example_test.go
versions.tf

- fix `provider_meta` value
- pin the cft dev_tools minor version
- fix the sample test

fix: provider_meta and test boilerplate

---

2-multitenant/envs/development/main.tf
2-multitenant/envs/development/outputs.tf
2-multitenant/envs/development/variables.tf
2-multitenant/envs/non-production/main.tf
2-multitenant/envs/non-production/outputs.tf
2-multitenant/envs/non-production/variables.tf
2-multitenant/envs/production/main.tf
2-multitenant/envs/production/outputs.tf
2-multitenant/envs/production/variables.tf
2-multitenant/modules/env_baseline/README.md
2-multitenant/modules/env_baseline/main.tf
2-multitenant/modules/env_baseline/outputs.tf
2-multitenant/modules/env_baseline/variables.tf
4-fleetscope/envs/development/main.tf
4-fleetscope/envs/development/variables.tf
4-fleetscope/envs/non-production/main.tf
4-fleetscope/envs/non-production/variables.tf
4-fleetscope/envs/production/main.tf
4-fleetscope/envs/production/variables.tf
test/integration/fleetscope/fleetscope_test.go
test/setup/README.md
test/setup/iam.tf
test/setup/main.tf
test/setup/outputs.tf
test/setup/variables.tf

- adds separate cluster and fleet projects in each env folder for the clusters and memberships respectively

feat: add cluster and fleet projects

---

2-multitenant/modules/env_baseline/main.tf
4-fleetscope/envs/development/main.tf
4-fleetscope/envs/non-production/main.tf
4-fleetscope/envs/production/main.tf
4-fleetscope/modules/env_baseline/README.md
4-fleetscope/modules/env_baseline/main.tf
4-fleetscope/modules/env_baseline/mcg.tf

added multiclusteringress hub feature for use by multiclustergateway

feat: added multiclusteringress hub feature for use by multiclustergateway

---

2-multitenant/modules/env_baseline/main.tf

- enable autoscaling balanced mode

feat(cluster): enabled balanced autoscaling

---

2-multitenant/modules/env_baseline/main.tf

- Switch to private cluster sub-module

feat(cluster): switch to private cluster

---

2-multitenant/modules/env_baseline/main.tf

- For now includes https://cloud.google.com/armor/docs/waf-rules#sql_injection_sqli

feat: add cloud armor policy

---

2-multitenant/modules/env_baseline/main.tf

- Enable workload identity at cluster creation

feat: enable workload identity

---

3-appfactory/apps/README.md
3-appfactory/apps/main.tf
3-appfactory/apps/outputs.tf
3-appfactory/apps/variables.tf
3-appfactory/modules/app-group-baseline/README.md
3-appfactory/modules/app-group-baseline/main.tf
3-appfactory/modules/app-group-baseline/outputs.tf
3-appfactory/modules/app-group-baseline/variables.tf
test/integration/appfactory/appfactory_test.go
test/integration/testutils/strings.go

This PR adds detailed integration tests for the resources created in the step `3-appfactory`
This PR also:
- updates the step `3-appfactory` to allow configuration of the location of the resources 
- adds additional bucket related variables
- sets the apply branches variable to consider the three branches

feat: add appfactory integration tests

---

2-multitenant/modules/env_baseline/main.tf

feat: adjusted sqli cloudarmor rule sensitivity level 1 to allow for cymbal bank app

---

4-fleetscope/modules/env_baseline/mcg.tf

fix(fleetscope): prevent possible race condition

---

3-appfactory/modules/app-group-baseline/main.tf
test/integration/appfactory/appfactory_test.go

fix(appfactory): add clouddeploy api to app admin project

---

4-fleetscope/envs/development/README.md
4-fleetscope/envs/development/main.tf
4-fleetscope/envs/development/variables.tf
4-fleetscope/envs/non-production/README.md
4-fleetscope/envs/non-production/main.tf
4-fleetscope/envs/non-production/variables.tf
4-fleetscope/envs/production/README.md
4-fleetscope/envs/production/variables.tf
4-fleetscope/modules/env_baseline/README.md
4-fleetscope/modules/env_baseline/policy.tf
4-fleetscope/modules/env_baseline/variables.tf
test/integration/fleetscope/fleetscope_test.go

- Add PoCo with PSS Baseline in audit mode
- (Re)add fleet_project_id to fleetscope

feat(fleetscope): add poco pss-baseline and fleet_project_id

---

build/int.cloudbuild.yaml
test/integration/appinfra/accounts_contacts_test.go
test/integration/appinfra/accounts_userservice_test.go
test/integration/appinfra/frontend_test.go
test/integration/appinfra/ledger_balancereader_test.go
test/integration/appinfra/ledger_ledgerwriter_test.go
test/integration/appinfra/ledger_transactionhistory_test.go
test/integration/appsource/accounts_contacts_test.go
test/integration/appsource/accounts_userservice_test.go
test/integration/appsource/frontend_test.go
test/integration/appsource/ledger_balancereader_test.go
test/integration/appsource/ledger_ledgerwriter_test.go
test/integration/appsource/ledger_transactionhistory_test.go

Split infra app test from source test

chore: split app test from infra test

---

test/integration/testutils/retry.go

chore(CI): retry concurrent policy changes

---

test/integration/testutils/retry.go

Fixes: https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/issues/134

chore(CI): retry compute engine api not enabled

---

.github/workflows/lint-tf-min.yaml
1-bootstrap/versions.tf
2-multitenant/envs/development/versions.tf
2-multitenant/envs/non-production/versions.tf
2-multitenant/envs/production/versions.tf
2-multitenant/modules/env_baseline/versions.tf
3-appfactory/apps/cymbal-bank/versions.tf
4-fleetscope/envs/development/versions.tf
4-fleetscope/envs/non-production/versions.tf
4-fleetscope/envs/production/versions.tf
5-appinfra/apps/cymbal-bank/accounts-contacts/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/development/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/non-production/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/production/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/frontend/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/ledger-balancereader/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/development/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/non-production/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/production/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/ledger-transactionhistory/envs/shared/versions.tf
5-appinfra/modules/cicd-pipeline/versions.tf
5-appinfra/modules/env_baseline/versions.tf
test/setup/versions.tf

- add PoC lint terraform minimum validate
- add tf needed `required_version`s

fix: add minimum TF version requirements

---

5-appinfra/apps/cymbal-bank/accounts-contacts/envs/shared/main.tf
5-appinfra/apps/cymbal-bank/accounts-contacts/envs/shared/variables.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/shared/main.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/shared/variables.tf
5-appinfra/apps/cymbal-bank/frontend/envs/shared/main.tf
5-appinfra/apps/cymbal-bank/frontend/envs/shared/variables.tf
5-appinfra/apps/cymbal-bank/ledger-balancereader/envs/shared/main.tf
5-appinfra/apps/cymbal-bank/ledger-balancereader/envs/shared/variables.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/shared/main.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/shared/variables.tf
5-appinfra/apps/cymbal-bank/ledger-transactionhistory/envs/shared/main.tf
5-appinfra/apps/cymbal-bank/ledger-transactionhistory/envs/shared/variables.tf
5-appinfra/modules/cicd-pipeline/README.md
5-appinfra/modules/cicd-pipeline/artifact-registry.tf
5-appinfra/modules/cicd-pipeline/cloud-deploy.tf
5-appinfra/modules/cicd-pipeline/locals.tf
5-appinfra/modules/cicd-pipeline/pipelines.tf
5-appinfra/modules/cicd-pipeline/project-iam-bindings.tf
5-appinfra/modules/cicd-pipeline/variables.tf
test/integration/appinfra/appinfra_test.go
test/integration/appsource/cymbal_bank_test.go

- Replace appinfra's hard coded prod/non-prod/dev environments with a configurable list

feat(appinfra): configurable envs

---

build/int.cloudbuild.yaml
test/integration/cymbal-bank/e2e_test.go

Rather than a fixed warm-up sleep, check at intervals up to a maximum qty.

chore(CI): webserver heartbeat check

---

test/integration/fleetscope/fleetscope_test.go
test/setup/main.tf

fix: update team name

---

test/integration/testutils/strings.go
test/setup/main.tf

Removes production and non-production tests.

chore: Reduces environments being tested to avoid naming conflicts

---

6-appsource/README.md

When deploying locally I took the initiative of updating the `6-appsource` docs with more information
The informations added were extracted from the `6-appsource` integration test code.

chore: more information on 6-appsource to deploy the application

---

3-fleetscope/modules/env_baseline/acm.tf

fix(fleetscope): add config_sync enable

---

test/integration/fleetscope/fleetscope_test.go

Fixes namespace check for nonprod and prod environments.

fix: Adds prefix at frontend namespace

---

.github/workflows/lint-tf-min.yaml
2-multitenant/envs/development/versions.tf
2-multitenant/envs/nonproduction/versions.tf
2-multitenant/envs/production/versions.tf
2-multitenant/modules/env_baseline/versions.tf
3-fleetscope/envs/development/versions.tf
3-fleetscope/envs/nonproduction/versions.tf
3-fleetscope/envs/production/versions.tf
4-appfactory/modules/app-group-baseline/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/development/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/nonproduction/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/production/versions.tf
5-appinfra/apps/cymbal-bank/accounts-userservice/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/frontend/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/ledger-balancereader/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/development/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/nonproduction/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/production/versions.tf
5-appinfra/apps/cymbal-bank/ledger-ledgerwriter/envs/shared/versions.tf
5-appinfra/apps/cymbal-bank/ledger-transactionhistory/envs/shared/versions.tf
5-appinfra/modules/alloydb-psc-setup/versions.tf
5-appinfra/modules/cicd-pipeline/versions.tf

Removes env versions.tf file
Fixes provider_metadata info

fix: fixes provider_metadata

---

1-bootstrap/tf_image.tf

missing parentheses in `create_cmd_body`

fix: adjust tf image cmd

---

test/integration/appsource/cymbal_bank_test.go
test/integration/appsource/cymbal_shop_test.go
test/integration/standalone_single_project/cymbal_bank_single_project_test.go

Adds retry on release command since it can take longer to be available.

chore: adds pool release

---

2-multitenant/modules/env_baseline/main.tf
6-appsource/hello-world/k8s-pod-arm64.yaml
6-appsource/hello-world/k8s-pod.yaml
test/integration/appinfra/appinfra_test.go

- Enable gVisor on Hello World example

feat(hello-world): enable gvisor

---

test/integration/appinfra/appinfra_test.go

chore(CI): remove Runf from appinfra

---

1-bootstrap/tf_image.tf
5-appinfra/modules/cicd-pipeline/cloud-storage.tf
5-appinfra/modules/cicd-pipeline/pipelines.tf
5-appinfra/modules/hpc-ai-training-infra/container_image.tf
5-appinfra/modules/hpc-monte-carlo-infra/bucket.tf
5-appinfra/modules/hpc-monte-carlo-infra/container_image.tf
test/setup/gitlab_vm.tf

Enables bucket versioning in all bucket created.

fix: enables bucket versioning
